name: Upload Videos to Telegram

on:
  workflow_dispatch:
    inputs:
      path:
        description: 'The path of the folder in PikPak containing video files to download'
        required: true
        default: 'example/path/'

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y ffmpeg
        pip install pyrogram moviepy opencv-python-headless requests

    - name: Set up Rclone
      run: |
        curl https://rclone.org/install.sh | sudo bash
        mkdir -p ~/.config/rclone
        echo '[pikpak]' > ~/.config/rclone/rclone.conf
        echo 'type = pikpak' >> ~/.config/rclone/rclone.conf
        echo 'user = udiskboot@gmail.com' >> ~/.config/rclone/rclone.conf
        echo 'pass = 1nhhx-0rSNold8UegWVDKnJCkWNaQKEh' >> ~/.config/rclone/rclone.conf
        echo 'token = {"access_token":"eyJhbGciOiJSUzI1NiIsImtpZCI6ImYyMGQ5NGU5LWNjNDYtNGFkZi04MjM1LWQ4YjI1ZjQyOGRiYiJ9.eyJpc3MiOiJodHRwczovL3VzZXIubXlwaWtwYWsuY29tIiwic3ViIjoiWXhWOExQNzVZQnFVMnpGUiIsImF1ZCI6IllOeFQ5dzdHTWRXdkVPS2EiLCJleHAiOjE3MjE1NTMxOTUsImlhdCI6MTcyMTU0NTk5NSwiYXRfaGFzaCI6InIuc3Rsa2tFY3dFZS1yMEFxNXFzNzlHUSIsInNjb3BlIjoidXNlciBwYW4gc3luYyBvZmZsaW5lIiwicHJvamVjdF9pZCI6IjJ3a3M1NmMzMWRjODBzeG01cDkiLCJtZXRhIjp7ImEiOiJmRlBoUGdFNWlqMTE3OTdlMEhPQ3QvbXpUTVFXZHNYWjBYWHFSZEJRUWNFPSJ9fQ.elP61zgPz4m9Lq5JC6kCSMjXjIqkxhnAWZ5KpSD0mEk3fEMxLI_JVMUG8_wlfTfzUQuJU426jsOWsPLzWkVnzkAiZ_qnLrnfy9HKxsHH5Kj2PaYKBnyX1M-X-FsmpRO2NR29RmZiIXLxdbc3mtOe9dF89Fk8K9Cd4kulhbTS7QGsq7rMzftdqsrWoSYMK-CPbbJ0dxYZ5vO7rAJjC4PeLFRvG5_5vNtlr3B_wkyG_qtw9X-epx4jFLskhLLtByADy1J_JJGx_ZC8oFUXsW6whdM-Fs52X_QIN36Yi_nAEGgXD2btUTm4t3B3MgMdk8KytKmC_iHCDf6Xlj3YpLRuHg","token_type":"Bearer","refresh_token":"os.S0jgnclQKmactQsZ7-suLfPQb4SusyK-WMud0JWaMlhn0jirgFRQZ_hLQrI2","expiry":"2024-07-21T17:13:14.921130723+08:00"}' >> ~/.config/rclone/rclone.conf

    - name: Download videos from PikPak
      run: |
        rclone copy pikpak:${{ github.event.inputs.path }} /tmp/videos --verbose --log-file=rclone.log || true
        cat rclone.log

    - name: Upload videos to Telegram
      run: |
        python3 upload_videos.py
      env:
        API_ID: 15468556
        API_HASH: "cfe6c02d6ac9b6416eaad381076887a9"
        BOT_TOKEN: "7136228670:AAEnXcaGNfO4m2B-DQpgf6sY1I8FhaSeUU0"
        CHAT_ID: "-1002158308340"
        VIDEO_DIR: "/tmp/videos"
